spring.application.name=werewolf

spring.datasource.url=jdbc:mysql://localhost:3306/werewolf_db
spring.datasource.username=werewolf_user
spring.datasource.password=werewolf_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true